In [1]:
# Import basic libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
# import dataset csv and show it
resultados = pd.read_csv("resultados.csv", sep=";")
resultados

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante
0,1928-29,1,10/02/1929,Arenas de Guecho,Athletic de Madrid,2,3
1,1928-29,1,10/02/1929,Español,Real Unión,3,2
2,1928-29,1,10/02/1929,Real Sociedad,Athletic Club,1,1
3,1928-29,1,10/02/1929,Real Madrid,Europa,5,0
4,1928-29,1,12/02/1929,Racing de Santander,Barcelona,0,2
...,...,...,...,...,...,...,...
26570,2022-23,38,04/06/2023,Celta de Vigo,Barcelona,-1,-1
26571,2022-23,38,04/06/2023,Valladolid,Getafe,-1,-1
26572,2022-23,38,04/06/2023,Elche,Cádiz,-1,-1
26573,2022-23,38,04/06/2023,Espanyol,Almería,-1,-1
26574,2022-23,38,04/06/2023,Osasuna,Girona,-1,-1

In [3]:
# Know column types in case I need to transform or operate with them
resultados.dtypes

Temporada         object
Jornada            int64
Fecha             object
Local             object
Visitante         object
GolesLocal         int64
GolesVisitante     int64
dtype: object

In [4]:
# Show nulls, NaNs and duplicates
print("\033[1mNans:\n\033[0m", resultados.isna().sum(), "\033[1m\n\nNulls:\n\033[0m", resultados.isnull().sum(), "\033[1m\n\nDuplicats:\n\033[0m", resultados.duplicated().sum())

Nans:
 Temporada         0
Jornada           0
Fecha             0
Local             0
Visitante         0
GolesLocal        0
GolesVisitante    0
dtype: int64

Nulls:
 Temporada         0
Jornada           0
Fecha             0
Local             0
Visitante         0
GolesLocal        0
GolesVisitante    0
dtype: int64

Duplicats:
 0

In [5]:
# Check name teams for unify names
print("Hi ha un total de", resultados.Local.nunique(), "i aquests son: \n", resultados.Local.unique())

Hi ha un total de 76 i aquests son:
 ['Arenas de Guecho' 'Español' 'Real Sociedad' 'Real Madrid'
 'Racing de Santander' 'Athletic Club' 'Athletic de Madrid' 'Barcelona'
 'Europa' 'Real Unión' 'Alavés' 'Unión Irún' 'Madrid' 'Donostia'
 'Valencia' 'Betis' 'Oviedo' 'Sevilla' 'Hércules' 'Osasuna' 'Zaragoza'
 'Athletic Aviación' 'Celta de Vigo' 'Atlético Aviación'
 'Atlético de Bilbao' 'Murcia' 'Deportivo de La Coruña' 'Granada'
 'Castellón' 'Alicante CD' 'Sabadell' 'Gijón' 'Alcoyano'
 'Atlético de Madrid' 'Gimnástico de Tarragona' 'Valladolid' 'CD Málaga'
 'Lérida' 'Santander' 'Las Palmas' 'Atlético Tetuán' 'Jaén'
 'Cultural Leonesa' 'Condal' 'Elche' 'Mallorca' 'Tenerife' 'Córdoba'
 'Pontevedra' 'Levante' 'Sporting de Gijón' 'Burgos' 'Salamanca' 'Cádiz'
 'Rayo Vallecano' 'Recreativo de Huelva' 'AD Almería' 'Logroñés'
 'Real Burgos' 'Albacete' 'Lleida' 'Compostela' 'Espanyol' 'Mérida'
 'Extremadura' 'Villarreal' 'Málaga' 'Numancia' 'Getafe'
 'Gimnàstic de Tarragona' 'Almería' 'Xerez' 'Eibar' 'Leganés' 'Girona'
 'Huesca']

_podem veure que alguns equips es repeteixen ja que varia lleugerement el seu nom, anem a unificar-los_

In [6]:
# Teams I detected that are the same but have differents names
'''
1. Español, Espanyol
2. Real Madrid, Madrid
3. Athletic club, Atlético de Bilbao
4. Athletic de Madrid, Athletic Aviación, Atlético de Madrid
5. Gijón, Sporting de Gijón
6. Gimnástico de Tarragona, Gimnàstic de Tarragona
7. CD Málaga, Málaga
8. Santander, Racing de Santander
9. Lérida, Lleida
10. Real Burgos, Burgos
11. AD Almería, Almería
'''

# Unify names
resultados["Local"] = resultados["Local"].replace({"Español": "Espanyol", "AD Almería" : "Almería", 
"CD Málaga" : "Málaga", "Real Burgos" : "Burgos", "Madrid" : "Real Madrid", "Atlético de Bilbao" : "Athletic club", 
"Athletic de Madrid" : "Atlético de Madrid", "Athletic Aviación" : "Atlético de Madrid", "Gijón" : "Sporting de Gijón", 
"Gimnástico de Tarragona" : "Gimnàstic de Tarragona", "Santander" : "Racing de Santander", "Lérida" : "Lleida"})

resultados["Visitante"] = resultados["Visitante"].replace({"Español": "Espanyol", "AD Almería" : "Almería", 
"CD Málaga" : "Málaga", "Real Burgos" : "Burgos", "Madrid" : "Real Madrid", "Atlético de Bilbao" : "Athletic club", 
"Athletic de Madrid" : "Atlético de Madrid", "Athletic Aviación" : "Atlético de Madrid", "Gijón" : "Sporting de Gijón", 
"Gimnástico de Tarragona" : "Gimnàstic de Tarragona", "Santander" : "Racing de Santander", "Lérida" : "Lleida"})


# Check name teams for unify names
print("Hi ha un total de", resultados.Local.nunique(), "i aquests son: \n", resultados.Local.unique())

Hi ha un total de 65 i aquests son:
 ['Arenas de Guecho' 'Espanyol' 'Real Sociedad' 'Real Madrid'
 'Racing de Santander' 'Athletic Club' 'Atlético de Madrid' 'Barcelona'
 'Europa' 'Real Unión' 'Alavés' 'Unión Irún' 'Donostia' 'Valencia' 'Betis'
 'Oviedo' 'Sevilla' 'Hércules' 'Osasuna' 'Zaragoza' 'Celta de Vigo'
 'Atlético Aviación' 'Athletic club' 'Murcia' 'Deportivo de La Coruña'
 'Granada' 'Castellón' 'Alicante CD' 'Sabadell' 'Sporting de Gijón'
 'Alcoyano' 'Gimnàstic de Tarragona' 'Valladolid' 'Málaga' 'Lleida'
 'Las Palmas' 'Atlético Tetuán' 'Jaén' 'Cultural Leonesa' 'Condal' 'Elche'
 'Mallorca' 'Tenerife' 'Córdoba' 'Pontevedra' 'Levante' 'Burgos'
 'Salamanca' 'Cádiz' 'Rayo Vallecano' 'Recreativo de Huelva' 'Almería'
 'Logroñés' 'Albacete' 'Compostela' 'Mérida' 'Extremadura' 'Villarreal'
 'Numancia' 'Getafe' 'Xerez' 'Eibar' 'Leganés' 'Girona' 'Huesca']

### A partir d'aqui comencem a crear columnes pel nostre dataset

In [7]:
# Create a function for the values of our new column
def quiniela(resultat):
    if resultat["GolesLocal"] > resultat["GolesVisitante"]: 
        return "1" 
    elif resultat["GolesLocal"] < resultat["GolesVisitante"]: 
        return "2"
    else: 
        return "X"

# Create a new column with the result of the match in "quiniela" style
resultados["Quiniela"] =  resultados.apply(quiniela, axis = 1)

# Check is done correctly
resultados.head(10)

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela
0,1928-29,1,10/02/1929,Arenas de Guecho,Atlético de Madrid,2,3,2
1,1928-29,1,10/02/1929,Espanyol,Real Unión,3,2,1
2,1928-29,1,10/02/1929,Real Sociedad,Athletic Club,1,1,X
3,1928-29,1,10/02/1929,Real Madrid,Europa,5,0,1
4,1928-29,1,12/02/1929,Racing de Santander,Barcelona,0,2,2
5,1928-29,2,17/02/1929,Athletic Club,Espanyol,9,0,1
6,1928-29,2,17/02/1929,Atlético de Madrid,Real Sociedad,0,3,2
7,1928-29,2,17/02/1929,Barcelona,Real Madrid,1,2,2
8,1928-29,2,17/02/1929,Europa,Arenas de Guecho,5,2,1
9,1928-29,2,17/02/1929,Real Unión,Racing de Santander,3,1,1

In [8]:
# Create a function for the values of our new column
def puntosL(resultat):
    if resultat["GolesLocal"] > resultat["GolesVisitante"]: 
        return 3 
    elif resultat["GolesLocal"] < resultat["GolesVisitante"]: 
        return 0
    else: 
        return 1

# Create a function for the values of our new column
def puntosV(resultat):
    if resultat["GolesLocal"] > resultat["GolesVisitante"]: 
        return 0 
    elif resultat["GolesLocal"] < resultat["GolesVisitante"]: 
        return 3
    else: 
        return 1

# Create new columns of how many points get Local team and another with the away team
resultados["LP"] =  resultados.apply(puntosL, axis = 1)
resultados["VP"] =  resultados.apply(puntosV, axis = 1)

#Show first rows
resultados

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP
0,1928-29,1,10/02/1929,Arenas de Guecho,Atlético de Madrid,2,3,2,0,3
1,1928-29,1,10/02/1929,Espanyol,Real Unión,3,2,1,3,0
2,1928-29,1,10/02/1929,Real Sociedad,Athletic Club,1,1,X,1,1
3,1928-29,1,10/02/1929,Real Madrid,Europa,5,0,1,3,0
4,1928-29,1,12/02/1929,Racing de Santander,Barcelona,0,2,2,0,3
...,...,...,...,...,...,...,...,...,...,...
26570,2022-23,38,04/06/2023,Celta de Vigo,Barcelona,-1,-1,X,1,1
26571,2022-23,38,04/06/2023,Valladolid,Getafe,-1,-1,X,1,1
26572,2022-23,38,04/06/2023,Elche,Cádiz,-1,-1,X,1,1
26573,2022-23,38,04/06/2023,Espanyol,Almería,-1,-1,X,1,1
26574,2022-23,38,04/06/2023,Osasuna,Girona,-1,-1,X,1,1

In [9]:
# Create new variable with the names of the teams
teams = resultados.Local.unique()

# Create a bucle to itirate for each local team assign the mean of goals done in last 10 matches as a local team before this one. 
for team in teams:
    resultados.loc[resultados['Local'] == team, 'L10gf_cL'] = resultados[resultados['Local'] == team]['GolesLocal'].rolling(10).mean().shift(1)

In [10]:
# Check the bucle is working well
resultados[resultados["Local"] == "Barcelona"][["Local", "GolesLocal", "L10gf_cL"]]

           Local  GolesLocal  L10gf_cL
7      Barcelona           1       NaN
16     Barcelona           2       NaN
27     Barcelona           5       NaN
37     Barcelona           1       NaN
47     Barcelona           5       NaN
...          ...         ...       ...
26487  Barcelona           1       1.9
26511  Barcelona           4       1.7
26522  Barcelona           1       1.7
26537  Barcelona          -1       1.6
26557  Barcelona          -1       1.4

[1495 rows x 3 columns]

In [11]:
# Create a bucle to itirate for each away team to assign the mean of goals done in last 10 matches as away team before this one.
for team in teams:
    resultados.loc[resultados['Visitante'] == team, 'V10gf_cV'] = resultados[resultados['Visitante'] == team]['GolesVisitante'].rolling(10).mean().shift(1)

In [12]:
# Create a bucle to itirate for each local team to assign the mean of goals recived in last 10 matches as a local team before this one. 
for team in teams:
    resultados.loc[resultados['Local'] == team, 'L10gc_cL'] = resultados[resultados['Local'] == team]['GolesVisitante'].rolling(10).mean().shift(1)

In [13]:
# Create a bucle to itirate for each away team to assign the mean of goals recived in last 10 matches as a away team before this one. 
for team in teams:
    resultados.loc[resultados['Visitante'] == team, 'V10gc_cV'] = resultados[resultados['Visitante'] == team]['GolesLocal'].rolling(10).mean().shift(1)

In [14]:
# Create a bucle to itirate for each local team to assign the mean of points did in last 10 matches as a local team before this one. 
for team in teams:
    resultados.loc[resultados['Local'] == team, 'L10r'] = resultados[resultados['Local'] == team]['LP'].rolling(10).mean().shift(1)

In [15]:
# Create a bucle to itirate for each away team to assign the mean of points did in last 10 matches as a away team before this one. 
for team in teams:
    resultados.loc[resultados['Visitante'] == team, 'V10r'] = resultados[resultados['Visitante'] == team]['VP'].rolling(10).mean().shift(1)

In [16]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):
    
    # Get last 10 rows before for the local team
    it_10r = resultados[(resultados['Local'] == resultados.loc[i, 'Local']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "1" in last 10 rows
    resultados.loc[i, 'LV_10cL'] = it_10r[it_10r['Quiniela'] == '1'].shape[0]

In [17]:
# Check the bucle is working well
resultados[(resultados["Local"] == "Barcelona") & (resultados["Quiniela"] == "1")][["Local", "Quiniela", "LV_10cL"]]

           Local Quiniela  LV_10cL
27     Barcelona        1      0.0
37     Barcelona        1      1.0
47     Barcelona        1      2.0
58     Barcelona        1      3.0
69     Barcelona        1      4.0
...          ...      ...      ...
26426  Barcelona        1      9.0
26445  Barcelona        1      9.0
26487  Barcelona        1      8.0
26511  Barcelona        1      8.0
26522  Barcelona        1      8.0

[1133 rows x 3 columns]

In [18]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):

    # Get last 10 rows before for the local team
    it_10r = resultados[(resultados['Local'] == resultados.loc[i, 'Local']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "X" in last 10 rows
    resultados.loc[i, 'LE_10cL'] = it_10r[it_10r['Quiniela'] == 'X'].shape[0]

In [19]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):

    # Get last 10 rows before for the local team
    it_10r = resultados[(resultados['Local'] == resultados.loc[i, 'Local']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "2" in last 10 rows
    resultados.loc[i, 'LF_10cL'] = it_10r[it_10r['Quiniela'] == '2'].shape[0]

In [20]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):

    # Get last 10 rows before for the away team
    it_10r = resultados[(resultados['Visitante'] == resultados.loc[i, 'Visitante']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "2" in last 10 rows
    resultados.loc[i, 'VV_10cV'] = it_10r[it_10r['Quiniela'] == '2'].shape[0]

In [21]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):

    # Get last 10 rows before for the away team
    it_10r = resultados[(resultados['Visitante'] == resultados.loc[i, 'Visitante']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "X" in last 10 rows
    resultados.loc[i, 'VE_10cV'] = it_10r[it_10r['Quiniela'] == 'X'].shape[0]

In [22]:
# Create a bucle to itirate each row of df
for i in range(len(resultados)):

    # Get last 10 rows before for the away team
    it_10r = resultados[(resultados['Visitante'] == resultados.loc[i, 'Visitante']) & (resultados.index < i)].tail(10)
    
    # Create a new colums where add the result for each iteration of how many times appears "1" in last 10 rows
    resultados.loc[i, 'VD_10cV'] = it_10r[it_10r['Quiniela'] == '1'].shape[0]

In [23]:
# Check dataset last rows of one team
resultados[resultados["Visitante"] == "Barcelona"].tail(25)

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP,...,L10gc_cL,V10gc_cV,L10r,V10r,LV_10cL,LE_10cL,LF_10cL,VV_10cV,VE_10cV,VD_10cV
26084,2021-22,27,06/03/2022,Elche,Barcelona,1,2,2,0,3,...,1.1,1.3,1.8,1.6,5.0,3.0,2.0,4.0,4.0,2.0
26101,2021-22,29,20/03/2022,Real Madrid,Barcelona,0,4,2,0,3,...,0.6,1.2,2.4,1.9,7.0,3.0,0.0,5.0,4.0,1.0
26118,2021-22,31,10/04/2022,Levante,Barcelona,2,3,2,0,3,...,1.4,1.1,1.2,2.2,3.0,3.0,4.0,6.0,4.0,0.0
26143,2021-22,33,21/04/2022,Real Sociedad,Barcelona,0,1,2,0,3,...,0.5,1.0,1.8,2.4,5.0,3.0,2.0,7.0,3.0,0.0
26157,2021-22,35,07/05/2022,Betis,Barcelona,1,2,2,0,3,...,1.1,0.9,1.8,2.4,6.0,0.0,4.0,7.0,3.0,0.0
26180,2021-22,37,15/05/2022,Getafe,Barcelona,0,0,X,1,1,...,0.6,0.8,1.9,2.6,5.0,4.0,1.0,8.0,2.0,0.0
26209,2022-23,2,21/08/2022,Real Sociedad,Barcelona,1,4,2,0,3,...,0.3,0.8,2.0,2.4,6.0,2.0,2.0,7.0,3.0,0.0
26233,2022-23,4,03/09/2022,Sevilla,Barcelona,0,3,2,0,3,...,1.0,0.8,1.7,2.6,4.0,5.0,1.0,8.0,2.0,0.0
26242,2022-23,5,10/09/2022,Cádiz,Barcelona,0,4,2,0,3,...,1.2,0.8,1.2,2.6,3.0,3.0,4.0,8.0,2.0,0.0
26263,2022-23,7,01/10/2022,Mallorca,Barcelona,0,1,2,0,3,...,1.7,0.6,1.6,2.8,5.0,1.0,4.0,9.0,1.0,0.0
26278,2022-23,9,16/10/2022,Real Madrid,Barcelona,3,1,1,3,0,...,0.8,0.5,2.3,2.8,7.0,2.0,1.0,9.0,1.0,0.0
26312,2022-23,12,29/10/2022,Valencia,Barcelona,0,1,2,0,3,...,1.2,0.7,1.4,2.5,4.0,2.0,4.0,8.0,1.0,1.0
26334,2022-23,14,08/11/2022,Osasuna,Barcelona,1,2,2,0,3,...,1.2,0.7,1.6,2.5,5.0,1.0,4.0,8.0,1.0,1.0
26346,2022-23,16,08/01/2023,Atlético de Madrid,Barcelona,0,1,2,0,3,...,0.9,0.6,1.6,2.5,4.0,4.0,2.0,8.0,1.0,1.0
26356,2022-23,17,01/02/2023,Betis,Barcelona,1,2,2,0,3,...,0.7,0.6,2.0,2.5,6.0,2.0,2.0,8.0,1.0,1.0
26381,2022-23,19,28/01/2023,Girona,Barcelona,0,1,2,0,3,...,1.6,0.6,1.5,2.5,4.0,3.0,3.0,8.0,1.0,1.0
26399,2022-23,21,12/02/2023,Villarreal,Barcelona,0,1,2,0,3,...,0.9,0.6,1.9,2.7,6.0,1.0,3.0,9.0,0.0,1.0
26418,2022-23,23,26/02/2023,Almería,Barcelona,1,0,1,3,0,...,1.3,0.5,1.9,2.7,6.0,1.0,3.0,9.0,0.0,1.0
26436,2022-23,25,12/03/2023,Athletic Club,Barcelona,0,1,2,0,3,...,1.0,0.6,1.6,2.4,5.0,1.0,4.0,8.0,0.0,2.0
26462,2022-23,27,01/04/2023,Elche,Barcelona,0,4,2,0,3,...,1.5,0.6,0.6,2.4,1.0,3.0,6.0,8.0,0.0,2.0
26476,2022-23,29,16/04/2023,Getafe,Barcelona,0,0,X,1,1,...,0.9,0.6,1.5,2.4,4.0,3.0,3.0,8.0,0.0,2.0
26500,2022-23,31,26/04/2023,Rayo Vallecano,Barcelona,2,1,1,3,0,...,1.2,0.3,1.3,2.5,3.0,4.0,3.0,8.0,1.0,1.0
26529,2022-23,34,14/05/2023,Espanyol,Barcelona,-1,-1,X,1,1,...,1.3,0.5,1.2,2.2,3.0,3.0,4.0,7.0,1.0,2.0
26551,2022-23,36,24/05/2023,Valladolid,Barcelona,-1,-1,X,1,1,...,1.4,0.3,1.2,2.0,3.0,3.0,4.0,6.0,2.0,2.0
26570,2022-23,38,04/06/2023,Celta de Vigo,Barcelona,-1,-1,X,1,1,...,0.3,0.2,1.6,1.8,4.0,4.0,2.0,5.0,3.0,2.0

In [24]:
resultados.columns

Index(['Temporada', 'Jornada', 'Fecha', 'Local', 'Visitante', 'GolesLocal',
       'GolesVisitante', 'Quiniela', 'LP', 'VP', 'L10gf_cL', 'V10gf_cV',
       'L10gc_cL', 'V10gc_cV', 'L10r', 'V10r', 'LV_10cL', 'LE_10cL', 'LF_10cL',
       'VV_10cV', 'VE_10cV', 'VD_10cV'],
      dtype='object')

In [25]:
# Import date library
import datetime

# Transforme dtype and format of date column
resultados["Fecha"] = pd.to_datetime(resultados["Fecha"], format = "%d/%m/%Y")

# Create a function to assign each date to a period of the season (decided by my criteria that could influence into results)
def periode(Fecha):
    if Fecha.month >= 8 and Fecha.month <= 10:
        return "1"
    elif Fecha.month >= 11 or Fecha.month <= 1:
        return "2"
    elif Fecha.month >= 2 and Fecha.month <= 4:
        return "3"
    else:
        return "4"

# Create the column with the function applied    
resultados["Periode"] = resultados["Fecha"].apply(periode)

# Check it works/did it correctly
resultados[resultados["Periode"] == "2"][["Temporada", "Fecha", "Periode"]].head(25)

    Temporada      Fecha Periode
90    1929-30 1929-12-01       2
91    1929-30 1929-12-01       2
92    1929-30 1929-12-01       2
93    1929-30 1929-12-01       2
94    1929-30 1929-12-01       2
95    1929-30 1929-12-08       2
96    1929-30 1929-12-08       2
97    1929-30 1929-12-08       2
98    1929-30 1929-12-08       2
99    1929-30 1929-12-08       2
100   1929-30 1929-12-15       2
101   1929-30 1929-12-15       2
102   1929-30 1929-12-15       2
103   1929-30 1929-12-15       2
104   1929-30 1929-12-15       2
105   1929-30 1929-12-22       2
106   1929-30 1929-12-22       2
107   1929-30 1929-12-22       2
108   1929-30 1929-12-22       2
109   1929-30 1929-12-22       2
110   1929-30 1929-12-29       2
111   1929-30 1929-12-29       2
112   1929-30 1929-12-29       2
113   1929-30 1929-12-29       2
114   1929-30 1929-12-29       2

### Canviem de dataset amb el qual també treballerem.

In [26]:
# Import csv file and create a new df
classificacio = pd.read_csv("clasificacio.csv", sep=";", encoding="latin-1")

# Show it
classificacio

     Temporada  Posicion            Equipo  PT
0      1928-29         1         Barcelona  25
1      1928-29         2       Real Madrid  23
2      1928-29         3     Athletic Club  20
3      1928-29         4     Real Sociedad  20
4      1928-29         5  Arenas de Guecho  19
...        ...       ...               ...  ..
1577   2022-23        16             Cádiz  35
1578   2022-23        17        Valladolid  35
1579   2022-23        18            Getafe  34
1580   2022-23        19          Espanyol  31
1581   2022-23        20             Elche  19

[1582 rows x 4 columns]

In [27]:
# Show how many seasons are
print("Hi ha", classificacio["Temporada"].nunique(), "temporades.")

Hi ha 92 temporades.

In [28]:
# Create a new variable with all the teams
c_teams = classificacio["Equipo"].unique()

# Create a new bucle to know the position mean of last 10 seasons before the actual and assign in a new column.
for team in c_teams:
    classificacio.loc[classificacio['Equipo'] == team, '10_Clas'] = classificacio[classificacio['Equipo'] == team]['Posicion'].rolling(10).mean().shift(1)

# Check it is working correctly 
classificacio[classificacio["Equipo"] == "Barcelona"].head(15)

    Temporada  Posicion     Equipo  PT  10_Clas
0     1928-29         1  Barcelona  25      NaN
11    1929-30         2  Barcelona  23      NaN
23    1930-31         4  Barcelona  21      NaN
32    1931-32         3  Barcelona  24      NaN
43    1932-33         4  Barcelona  19      NaN
58    1933-34         9  Barcelona  16      NaN
65    1934-35         6  Barcelona  24      NaN
76    1935-36         5  Barcelona  24      NaN
92    1939-40         9  Barcelona  19      NaN
99    1940-41         4  Barcelona  27      NaN
119   1941-42        12  Barcelona  19      4.7
124   1942-43         3  Barcelona  32      5.8
141   1943-44         6  Barcelona  28      5.9
150   1944-45         1  Barcelona  39      6.1
165   1945-46         2  Barcelona  35      5.9

In [29]:
# Print max and min of the new column to know the range
print(classificacio["10_Clas"].max())
print(classificacio["10_Clas"].min())

16.5
1.2

In [30]:
# Create a function a apply a handicap depending of the position of each time in last 10 season.
def handicap(x):
    if x <= 3:
        return "1"
    elif 3 < x <= 7:
        return "2"
    elif 7 < x < 14:
        return "3"
    else:
        return "4"

# Create the new column applying the handicap function
classificacio["Handicap"] = classificacio["10_Clas"].apply(handicap)

# Check it is working correctly
classificacio[classificacio["Equipo"] == "Madrid"]

   Temporada  Posicion  Equipo  PT  10_Clas Handicap
30   1931-32         1  Madrid  28      NaN        4
40   1932-33         1  Madrid  28      NaN        4
51   1933-34         2  Madrid  22      NaN        4
61   1934-35         2  Madrid  33      NaN        4
73   1935-36         2  Madrid  29      NaN        4

In [31]:
# Check name teams for unify names
print("Hay unn total de", classificacio.Equipo.nunique(), "y estos son: \n", classificacio.Equipo.unique())

Hay unn total de 76 y estos son:
 ['Barcelona' 'Real Madrid' 'Athletic Club' 'Real Sociedad'
 'Arenas de Guecho' 'Athletic de Madrid' 'Español' 'Europa' 'Real Unión'
 'Racing de Santander' 'Alavés' 'Madrid' 'Valencia' 'Donostia'
 'Unión Irún' 'Betis' 'Oviedo' 'Sevilla' 'Hércules' 'Osasuna'
 'Athletic Aviación' 'Zaragoza' 'Celta de Vigo' 'Atlético Aviación'
 'Atlético de Bilbao' 'Murcia' 'Deportivo de La Coruña' 'Castellón'
 'Granada' 'Alicante CD' 'Sabadell' 'Gijón' 'Alcoyano'
 'Atlético de Madrid' 'Gimnástico de Tarragona' 'Valladolid' 'CD Málaga'
 'Santander' 'Lérida' 'Las Palmas' 'Atlético Tetuán' 'Jaén'
 'Cultural Leonesa' 'Condal' 'Elche' 'Mallorca' 'Tenerife' 'Córdoba'
 'Levante' 'Pontevedra' 'Sporting de Gijón' 'Burgos' 'Salamanca'
 'Rayo Vallecano' 'Cádiz' 'Recreativo de Huelva' 'AD Almería' 'Logroñés'
 'Real Burgos' 'Albacete' 'Lleida' 'Compostela' 'Espanyol' 'Mérida'
 'Extremadura' 'Villarreal' 'Málaga' 'Numancia' 'Getafe'
 'Gimnàstic de Tarragona' 'Almería' 'Xerez' 'Eibar' 'Leganés' 'Girona'
 'Huesca']

In [32]:
'''
1. Español, Espanyol
2. Real Madrid, Madrid
3. Athletic club, Atlético de Bilbao
4. Athletic de Madrid, Athletic Aviación, Atlético de Madrid
5. Gijón, Sporting de Gijón
6. Gimnástico de Tarragona, Gimnàstic de Tarragona
7. CD Málaga, Málaga
8. Santander, Racing de Santander
9. Lérida, Lleida
10. Real Burgos, Burgos
11. AD Almería, Almería
'''

# Unify names
classificacio["Equipo"] = classificacio["Equipo"].replace({"Español": "Espanyol", "AD Almería" : "Almería", 
"CD Málaga" : "Málaga", "Real Burgos" : "Burgos", "Madrid" : "Real Madrid", "Atlético de Bilbao" : "Athletic club", 
"Athletic de Madrid" : "Atlético de Madrid", "Athletic Aviación" : "Atlético de Madrid", "Gijón" : "Sporting de Gijón", 
"Gimnástico de Tarragona" : "Gimnàstic de Tarragona", "Santander" : "Racing de Santander", "Lérida" : "Lleida"})

# Check name teams for unify names
print("Hay unn total de", classificacio.Equipo.nunique(), "y estos son: \n", classificacio.Equipo.unique())

Hay unn total de 65 y estos son:
 ['Barcelona' 'Real Madrid' 'Athletic Club' 'Real Sociedad'
 'Arenas de Guecho' 'Atlético de Madrid' 'Espanyol' 'Europa' 'Real Unión'
 'Racing de Santander' 'Alavés' 'Valencia' 'Donostia' 'Unión Irún' 'Betis'
 'Oviedo' 'Sevilla' 'Hércules' 'Osasuna' 'Zaragoza' 'Celta de Vigo'
 'Atlético Aviación' 'Athletic club' 'Murcia' 'Deportivo de La Coruña'
 'Castellón' 'Granada' 'Alicante CD' 'Sabadell' 'Sporting de Gijón'
 'Alcoyano' 'Gimnàstic de Tarragona' 'Valladolid' 'Málaga' 'Lleida'
 'Las Palmas' 'Atlético Tetuán' 'Jaén' 'Cultural Leonesa' 'Condal' 'Elche'
 'Mallorca' 'Tenerife' 'Córdoba' 'Levante' 'Pontevedra' 'Burgos'
 'Salamanca' 'Rayo Vallecano' 'Cádiz' 'Recreativo de Huelva' 'Almería'
 'Logroñés' 'Albacete' 'Compostela' 'Mérida' 'Extremadura' 'Villarreal'
 'Numancia' 'Getafe' 'Xerez' 'Eibar' 'Leganés' 'Girona' 'Huesca']

**Aplicarem la columna classificacio ["Handicap"] al df results**

In [33]:
# Merge the columns i am interested to add in resultados df
resultados = resultados.merge(classificacio[['Temporada', 'Equipo', 'Handicap']], left_on=['Temporada', 'Local'], right_on=['Temporada', 'Equipo'], how='left')

# Rename column
resultados = resultados.rename(columns={'Handicap': 'L_Handicap'})

# Check the merge is done
resultados.tail(25)

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP,...,V10r,LV_10cL,LE_10cL,LF_10cL,VV_10cV,VE_10cV,VD_10cV,Periode,Equipo,L_Handicap
26550,2022-23,36,2023-05-24,Espanyol,Atlético de Madrid,-1,-1,X,1,1,...,1.8,3.0,4.0,3.0,5.0,3.0,2.0,4,Espanyol,3
26551,2022-23,36,2023-05-24,Valladolid,Barcelona,-1,-1,X,1,1,...,2.0,3.0,3.0,4.0,6.0,2.0,2.0,4,Valladolid,4
26552,2022-23,36,2023-05-24,Villarreal,Cádiz,-1,-1,X,1,1,...,1.0,5.0,2.0,3.0,2.0,4.0,4.0,4,Villarreal,3
26553,2022-23,36,2023-05-24,Real Madrid,Rayo Vallecano,-1,-1,X,1,1,...,1.0,6.0,3.0,1.0,2.0,4.0,4.0,4,Real Madrid,1
26554,2022-23,36,2023-05-24,Real Sociedad,Almería,-1,-1,X,1,1,...,0.7,6.0,3.0,1.0,1.0,4.0,5.0,4,Real Sociedad,3
26555,2022-23,37,2023-05-28,Athletic Club,Elche,-1,-1,X,1,1,...,0.5,2.0,3.0,5.0,1.0,2.0,7.0,4,Athletic Club,3
26556,2022-23,37,2023-05-28,Atlético de Madrid,Real Sociedad,-1,-1,X,1,1,...,1.3,8.0,2.0,0.0,3.0,4.0,3.0,4,Atlético de Madrid,1
26557,2022-23,37,2023-05-28,Barcelona,Mallorca,-1,-1,X,1,1,...,0.5,8.0,2.0,0.0,1.0,2.0,7.0,4,Barcelona,1
26558,2022-23,37,2023-05-28,Getafe,Osasuna,-1,-1,X,1,1,...,1.1,4.0,3.0,3.0,2.0,5.0,3.0,4,Getafe,3
26559,2022-23,37,2023-05-28,Cádiz,Celta de Vigo,-1,-1,X,1,1,...,1.0,4.0,3.0,3.0,2.0,4.0,4.0,4,Cádiz,4
26560,2022-23,37,2023-05-28,Rayo Vallecano,Villarreal,-1,-1,X,1,1,...,1.5,4.0,4.0,2.0,4.0,3.0,3.0,4,Rayo Vallecano,4
26561,2022-23,37,2023-05-28,Almería,Valladolid,-1,-1,X,1,1,...,0.8,4.0,3.0,3.0,2.0,2.0,6.0,4,Almería,4
26562,2022-23,37,2023-05-28,Girona,Betis,-1,-1,X,1,1,...,1.4,7.0,1.0,2.0,4.0,2.0,4.0,4,Girona,4
26563,2022-23,37,2023-05-28,Valencia,Espanyol,-1,-1,X,1,1,...,0.7,3.0,4.0,3.0,2.0,1.0,7.0,4,Valencia,3
26564,2022-23,37,2023-05-28,Sevilla,Real Madrid,-1,-1,X,1,1,...,1.1,6.0,2.0,2.0,3.0,2.0,5.0,4,Sevilla,2
26565,2022-23,38,2023-06-04,Betis,Valencia,-1,-1,X,1,1,...,0.5,3.0,4.0,3.0,1.0,2.0,7.0,4,Betis,3
26566,2022-23,38,2023-06-04,Mallorca,Rayo Vallecano,-1,-1,X,1,1,...,1.0,4.0,5.0,1.0,2.0,4.0,4.0,4,Mallorca,3
26567,2022-23,38,2023-06-04,Real Sociedad,Sevilla,-1,-1,X,1,1,...,1.2,5.0,4.0,1.0,3.0,3.0,4.0,4,Real Sociedad,3
26568,2022-23,38,2023-06-04,Real Madrid,Athletic Club,-1,-1,X,1,1,...,1.6,5.0,4.0,1.0,4.0,4.0,2.0,4,Real Madrid,1
26569,2022-23,38,2023-06-04,Villarreal,Atlético de Madrid,-1,-1,X,1,1,...,1.9,4.0,3.0,3.0,5.0,4.0,1.0,4,Villarreal,3
26570,2022-23,38,2023-06-04,Celta de Vigo,Barcelona,-1,-1,X,1,1,...,1.8,4.0,4.0,2.0,5.0,3.0,2.0,4,Celta de Vigo,3
26571,2022-23,38,2023-06-04,Valladolid,Getafe,-1,-1,X,1,1,...,0.5,3.0,4.0,3.0,0.0,5.0,5.0,4,Valladolid,4
26572,2022-23,38,2023-06-04,Elche,Cádiz,-1,-1,X,1,1,...,0.8,2.0,4.0,4.0,1.0,5.0,4.0,4,Elche,4
26573,2022-23,38,2023-06-04,Espanyol,Almería,-1,-1,X,1,1,...,0.7,3.0,4.0,3.0,1.0,4.0,5.0,4,Espanyol,3
26574,2022-23,38,2023-06-04,Osasuna,Girona,-1,-1,X,1,1,...,1.0,3.0,3.0,4.0,2.0,4.0,4.0,4,Osasuna,3

In [34]:
# Merge the columns i am interested to add in resultados df
resultados = resultados.merge(classificacio[['Temporada', 'Equipo', 'Handicap']], left_on=['Temporada', 'Visitante'], right_on=['Temporada', 'Equipo'], how='left')

# Rename column
resultados = resultados.rename(columns={'Handicap': 'V_Handicap'})

# Drop columns which are repeated
resultados = resultados.drop(columns = ["Equipo_x", "Equipo_y"])

# Check df
resultados[resultados["Local"] == "Barcelona"]

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP,...,V10r,LV_10cL,LE_10cL,LF_10cL,VV_10cV,VE_10cV,VD_10cV,Periode,L_Handicap,V_Handicap
7,1928-29,2,1929-02-17,Barcelona,Real Madrid,1,2,2,0,3,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,3,4,4
16,1928-29,4,1929-03-03,Barcelona,Arenas de Guecho,2,2,X,1,1,...,NaN,0.0,0.0,1.0,0.0,0.0,1.0,3,4,4
27,1928-29,6,1929-03-24,Barcelona,Europa,5,2,1,3,0,...,NaN,0.0,1.0,1.0,0.0,0.0,3.0,3,4,4
37,1928-29,8,1929-04-07,Barcelona,Espanyol,1,0,1,3,0,...,NaN,1.0,1.0,1.0,0.0,1.0,1.0,3,4,4
47,1928-29,10,1929-04-28,Barcelona,Racing de Santander,5,1,1,3,0,...,NaN,2.0,1.0,1.0,0.0,0.0,5.0,3,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26487,2022-23,30,2023-04-23,Barcelona,Atlético de Madrid,1,0,1,3,0,...,2.0,8.0,2.0,0.0,6.0,2.0,2.0,3,1,1
26511,2022-23,32,2023-04-29,Barcelona,Betis,4,0,1,3,0,...,1.6,8.0,2.0,0.0,5.0,1.0,4.0,3,1,3
26522,2022-23,33,2023-05-02,Barcelona,Osasuna,1,0,1,3,0,...,1.1,8.0,2.0,0.0,2.0,5.0,3.0,4,1,3
26537,2022-23,35,2023-05-21,Barcelona,Real Sociedad,-1,-1,X,1,1,...,1.5,8.0,2.0,0.0,4.0,3.0,3.0,4,1,3
26557,2022-23,37,2023-05-28,Barcelona,Mallorca,-1,-1,X,1,1,...,0.5,8.0,2.0,0.0,1.0,2.0,7.0,4,1,3

In [35]:
# Find the rows of the games that are still not played
resultados.loc[resultados["GolesLocal"]==-1]

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP,...,V10r,LV_10cL,LE_10cL,LF_10cL,VV_10cV,VE_10cV,VD_10cV,Periode,L_Handicap,V_Handicap
26525,2022-23,34,2023-05-14,Betis,Rayo Vallecano,-1,-1,X,1,1,...,1.2,3.0,4.0,3.0,3.0,3.0,4.0,4,3,4
26526,2022-23,34,2023-05-14,Celta de Vigo,Valencia,-1,-1,X,1,1,...,0.3,4.0,3.0,3.0,1.0,0.0,9.0,4,3,3
26527,2022-23,34,2023-05-14,Villarreal,Athletic Club,-1,-1,X,1,1,...,1.5,6.0,1.0,3.0,4.0,3.0,3.0,4,3,3
26528,2022-23,34,2023-05-14,Elche,Atlético de Madrid,-1,-1,X,1,1,...,1.7,2.0,2.0,6.0,5.0,2.0,3.0,4,4,1
26529,2022-23,34,2023-05-14,Espanyol,Barcelona,-1,-1,X,1,1,...,2.2,3.0,3.0,4.0,7.0,1.0,2.0,4,3,1
26530,2022-23,34,2023-05-14,Real Madrid,Getafe,-1,-1,X,1,1,...,0.3,7.0,2.0,1.0,0.0,3.0,7.0,4,1,3
26531,2022-23,34,2023-05-14,Mallorca,Cádiz,-1,-1,X,1,1,...,0.9,6.0,3.0,1.0,2.0,3.0,5.0,4,3,4
26532,2022-23,34,2023-05-14,Valladolid,Sevilla,-1,-1,X,1,1,...,1.2,4.0,2.0,4.0,3.0,3.0,4.0,4,4,2
26533,2022-23,34,2023-05-14,Osasuna,Almería,-1,-1,X,1,1,...,0.6,4.0,1.0,5.0,1.0,3.0,6.0,4,3,4
26534,2022-23,34,2023-05-14,Real Sociedad,Girona,-1,-1,X,1,1,...,1.2,6.0,3.0,1.0,3.0,3.0,4.0,4,3,4
26535,2022-23,35,2023-05-21,Athletic Club,Celta de Vigo,-1,-1,X,1,1,...,1.2,3.0,2.0,5.0,3.0,3.0,4.0,4,3,3
26536,2022-23,35,2023-05-21,Atlético de Madrid,Osasuna,-1,-1,X,1,1,...,1.1,8.0,1.0,1.0,2.0,5.0,3.0,4,1,3
26537,2022-23,35,2023-05-21,Barcelona,Real Sociedad,-1,-1,X,1,1,...,1.5,8.0,2.0,0.0,4.0,3.0,3.0,4,1,3
26538,2022-23,35,2023-05-21,Cádiz,Valladolid,-1,-1,X,1,1,...,0.7,4.0,3.0,3.0,2.0,1.0,7.0,4,4,4
26539,2022-23,35,2023-05-21,Almería,Mallorca,-1,-1,X,1,1,...,0.4,4.0,2.0,4.0,1.0,1.0,8.0,4,4,3
26540,2022-23,35,2023-05-21,Girona,Villarreal,-1,-1,X,1,1,...,1.4,7.0,1.0,2.0,4.0,2.0,4.0,4,4,3
26541,2022-23,35,2023-05-21,Sevilla,Betis,-1,-1,X,1,1,...,1.6,7.0,1.0,2.0,5.0,1.0,4.0,4,2,3
26542,2022-23,35,2023-05-21,Getafe,Elche,-1,-1,X,1,1,...,0.4,5.0,2.0,3.0,1.0,1.0,8.0,4,3,4
26543,2022-23,35,2023-05-21,Rayo Vallecano,Espanyol,-1,-1,X,1,1,...,0.7,4.0,3.0,3.0,2.0,1.0,7.0,4,4,3
26544,2022-23,35,2023-05-21,Valencia,Real Madrid,-1,-1,X,1,1,...,1.3,4.0,3.0,3.0,4.0,1.0,5.0,4,3,1
26545,2022-23,36,2023-05-24,Betis,Getafe,-1,-1,X,1,1,...,0.4,3.0,4.0,3.0,0.0,4.0,6.0,4,3,3
26546,2022-23,36,2023-05-24,Celta de Vigo,Girona,-1,-1,X,1,1,...,1.0,4.0,4.0,2.0,2.0,4.0,4.0,4,3,4
26547,2022-23,36,2023-05-24,Elche,Sevilla,-1,-1,X,1,1,...,1.2,2.0,3.0,5.0,3.0,3.0,4.0,4,4,2
26548,2022-23,36,2023-05-24,Mallorca,Valencia,-1,-1,X,1,1,...,0.4,5.0,4.0,1.0,1.0,1.0,8.0,4,3,3
26549,2022-23,36,2023-05-24,Osasuna,Athletic Club,-1,-1,X,1,1,...,1.5,3.0,2.0,5.0,4.0,3.0,3.0,4,3,3
26550,2022-23,36,2023-05-24,Espanyol,Atlético de Madrid,-1,-1,X,1,1,...,1.8,3.0,4.0,3.0,5.0,3.0,2.0,4,3,1
26551,2022-23,36,2023-05-24,Valladolid,Barcelona,-1,-1,X,1,1,...,2.0,3.0,3.0,4.0,6.0,2.0,2.0,4,4,1
26552,2022-23,36,2023-05-24,Villarreal,Cádiz,-1,-1,X,1,1,...,1.0,5.0,2.0,3.0,2.0,4.0,4.0,4,3,4
26553,2022-23,36,2023-05-24,Real Madrid,Rayo Vallecano,-1,-1,X,1,1,...,1.0,6.0,3.0,1.0,2.0,4.0,4.0,4,1,4
26554,2022-23,36,2023-05-24,Real Sociedad,Almería,-1,-1,X,1,1,...,0.7,6.0,3.0,1.0,1.0,4.0,5.0,4,3,4
26555,2022-23,37,2023-05-28,Athletic Club,Elche,-1,-1,X,1,1,...,0.5,2.0,3.0,5.0,1.0,2.0,7.0,4,3,4
26556,2022-23,37,2023-05-28,Atlético de Madrid,Real Sociedad,-1,-1,X,1,1,...,1.3,8.0,2.0,0.0,3.0,4.0,3.0,4,1,3
26557,2022-23,37,2023-05-28,Barcelona,Mallorca,-1,-1,X,1,1,...,0.5,8.0,2.0,0.0,1.0,2.0,7.0,4,1,3
26558,2022-23,37,2023-05-28,Getafe,Osasuna,-1,-1,X,1,1,...,1.1,4.0,3.0,3.0,2.0,5.0,3.0,4,3,3
26559,2022-23,37,2023-05-28,Cádiz,Celta de Vigo,-1,-1,X,1,1,...,1.0,4.0,3.0,3.0,2.0,4.0,4.0,4,4,3
26560,2022-23,37,2023-05-28,Rayo Vallecano,Villarreal,-1,-1,X,1,1,...,1.5,4.0,4.0,2.0,4.0,3.0,3.0,4,4,3
26561,2022-23,37,2023-05-28,Almería,Valladolid,-1,-1,X,1,1,...,0.8,4.0,3.0,3.0,2.0,2.0,6.0,4,4,4
26562,2022-23,37,2023-05-28,Girona,Betis,-1,-1,X,1,1,...,1.4,7.0,1.0,2.0,4.0,2.0,4.0,4,4,3
26563,2022-23,37,2023-05-28,Valencia,Espanyol,-1,-1,X,1,1,...,0.7,3.0,4.0,3.0,2.0,1.0,7.0,4,3,3
26564,2022-23,37,2023-05-28,Sevilla,Real Madrid,-1,-1,X,1,1,...,1.1,6.0,2.0,2.0,3.0,2.0,5.0,4,2,1
26565,2022-23,38,2023-06-04,Betis,Valencia,-1,-1,X,1,1,...,0.5,3.0,4.0,3.0,1.0,2.0,7.0,4,3,3
26566,2022-23,38,2023-06-04,Mallorca,Rayo Vallecano,-1,-1,X,1,1,...,1.0,4.0,5.0,1.0,2.0,4.0,4.0,4,3,4
26567,2022-23,38,2023-06-04,Real Sociedad,Sevilla,-1,-1,X,1,1,...,1.2,5.0,4.0,1.0,3.0,3.0,4.0,4,3,2
26568,2022-23,38,2023-06-04,Real Madrid,Athletic Club,-1,-1,X,1,1,...,1.6,5.0,4.0,1.0,4.0,4.0,2.0,4,1,3
26569,2022-23,38,2023-06-04,Villarreal,Atlético de Madrid,-1,-1,X,1,1,...,1.9,4.0,3.0,3.0,5.0,4.0,1.0,4,3,1
26570,2022-23,38,2023-06-04,Celta de Vigo,Barcelona,-1,-1,X,1,1,...,1.8,4.0,4.0,2.0,5.0,3.0,2.0,4,3,1
26571,2022-23,38,2023-06-04,Valladolid,Getafe,-1,-1,X,1,1,...,0.5,3.0,4.0,3.0,0.0,5.0,5.0,4,4,3
26572,2022-23,38,2023-06-04,Elche,Cádiz,-1,-1,X,1,1,...,0.8,2.0,4.0,4.0,1.0,5.0,4.0,4,4,4
26573,2022-23,38,2023-06-04,Espanyol,Almería,-1,-1,X,1,1,...,0.7,3.0,4.0,3.0,1.0,4.0,5.0,4,3,4
26574,2022-23,38,2023-06-04,Osasuna,Girona,-1,-1,X,1,1,...,1.0,3.0,3.0,4.0,2.0,4.0,4.0,4,3,4

In [37]:
# Split dataset with two dataset (one with the information we already have to train the model, and the other with the results)
resultados_topredict = resultados[(resultados['Temporada'] == '2022-23') & (resultados['Jornada'] == 34)]
resultados = resultados.loc[resultados["GolesLocal"]!=-1]
resultados_topredict

,Temporada,Jornada,Fecha,Local,Visitante,GolesLocal,GolesVisitante,Quiniela,LP,VP,...,V10r,LV_10cL,LE_10cL,LF_10cL,VV_10cV,VE_10cV,VD_10cV,Periode,L_Handicap,V_Handicap
26525,2022-23,34,2023-05-14,Betis,Rayo Vallecano,-1,-1,X,1,1,...,1.2,3.0,4.0,3.0,3.0,3.0,4.0,4,3,4
26526,2022-23,34,2023-05-14,Celta de Vigo,Valencia,-1,-1,X,1,1,...,0.3,4.0,3.0,3.0,1.0,0.0,9.0,4,3,3
26527,2022-23,34,2023-05-14,Villarreal,Athletic Club,-1,-1,X,1,1,...,1.5,6.0,1.0,3.0,4.0,3.0,3.0,4,3,3
26528,2022-23,34,2023-05-14,Elche,Atlético de Madrid,-1,-1,X,1,1,...,1.7,2.0,2.0,6.0,5.0,2.0,3.0,4,4,1
26529,2022-23,34,2023-05-14,Espanyol,Barcelona,-1,-1,X,1,1,...,2.2,3.0,3.0,4.0,7.0,1.0,2.0,4,3,1
26530,2022-23,34,2023-05-14,Real Madrid,Getafe,-1,-1,X,1,1,...,0.3,7.0,2.0,1.0,0.0,3.0,7.0,4,1,3
26531,2022-23,34,2023-05-14,Mallorca,Cádiz,-1,-1,X,1,1,...,0.9,6.0,3.0,1.0,2.0,3.0,5.0,4,3,4
26532,2022-23,34,2023-05-14,Valladolid,Sevilla,-1,-1,X,1,1,...,1.2,4.0,2.0,4.0,3.0,3.0,4.0,4,4,2
26533,2022-23,34,2023-05-14,Osasuna,Almería,-1,-1,X,1,1,...,0.6,4.0,1.0,5.0,1.0,3.0,6.0,4,3,4
26534,2022-23,34,2023-05-14,Real Sociedad,Girona,-1,-1,X,1,1,...,1.2,6.0,3.0,1.0,3.0,3.0,4.0,4,3,4

In [38]:
# Import dataframe
resultados_topredict.to_csv("jornada34.csv", index = False)
resultados.to_csv("resultados_pfinal.csv", index = False)
classificacio.to_csv("classificacio_pfinal.csv", index = False)